name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

  watch:
    types: [started]

jobs:
  sync:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: Pana
          base: master
          head: feat-my-nrm